// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mapognbffsgecxvzrcgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hcG9nbmJmZnNnZWN4dnpyY2duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNDM5NjQsImV4cCI6MjA1OTkxOTk2NH0.72FTyL1MAyOPxFyYAwA7pXWjvYpt6fG9Xcr6nEgzCl4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);